### ISSUE TITLE
demo run error

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/c3dpo_nrsfm#7]
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb4322c4e10>: Failed to establish a new connection: [Errno 111] Connection refused

**Comment by davnov134** [comment]
Hi,

a similar issue was closed in https://github.com/facebookresearch/c3dpo_nrsfm/issues/1#issuecomment-547255161.

A quick recap: The error is due to an omission of starting a visdom server before executing `demo.py`. Please make sure to start the server first.

Despite the error, the demo script will still continue to run and dump the visualisation files.

... closing the issue.
